### ISSUE TITLE
Subsampling KITTI LiDAR lines

### ISSUE THREAD

**Issue by Divadi** [andreaconti/sparsity-agnostic-depth-completion#1]
Thank you for sharing your interesting work! I was wondering - what algorithm did you use to subsample the KITTI 64 lines to 4, 8, etc? It would be much appreciated if you could share a reference/code to do so.

Thank you!

**Comment by andreaconti** [comment]
Hi thank you for you interest in my work! To subsample lidar scanlines can be used the function from here

https://github.com/placeforyiming/RAL_Non-Learning_DepthCompletion/blob/d7f7e7d3143262419fc646a451ed46dc585892a0/subsample_Lidar_val.py#L157

Best, 
Andrea

**Comment by Divadi** [comment]
I see, thank you!
